[project]
name = "FocusView"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "nuitka>=2.7.14",
    "numpy>=2.3.3",
    "opencv-python>=4.11.0.86",
    "pyqt6>=6.4.2",
    "qt-material>=2.17",
]
